name: NodeJS/Angular github actions
on: [push]
jobs:
  NodeJS-Angular-GitHub-Actions:
    runs-on: macos-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Change directory
        run: |
          cd ${{ github.workspace }}
      - name: Install node monules
        run: |
          npm install
      - name: Run lint
        run: |
          npm run lint

      - name: Run test
        run: |
          npm run test
      - name: Run e2e
        run: |
          npm run e2e
      - run: echo "🍏 This job's status is ${{ job.status }}."

